name: "container modification  CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-container-modification-latest-job:
    name: "container modification ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "archlinux/blackarch"
      dockerfilename: "Dockerfile.archlinux.blackarch"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "Container modification"
      run: |
        docker run -d --name wordpress wluns32/wordpress-lamp
        docker container ls
        # find the modifications done to this container respecting to the image 
        #D - Deleted File
        #C - Changed File
        #A - Added File
        docker diff wordpress      
        # download it from the container to check for malicious activity with
        # Error: No such container:path: wordpress-orig:/etc/shadow
        # docker cp wordpress:/etc/shadow .
        docker cp wordpress:/var/lib/mysql/auto.cnf .
        ls -lai
        docker run -d --name wordpress-orig wluns32/wordpress-lamp
        docker container ls
        docker diff wordpress 
        # compare it with the original one running a new container 
        docker cp wordpress-orig:/var/lib/mysql/auto.cnf auto.cnf_shadow
        ls -lai
        # diff original_shadow shadow
        diff auto.cnf_shadow auto.cnf > auto.conf_diff.txt
        cat auto.conf_diff.txt
        # # access the container and check it, non-interactive
        docker container ls
        docker exec wordpress ls -lai /var/lib/mysql
 
