name: "docker vuln scanners CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  
  ubuntu-latest-wapiti-job:
    name: "wapiti ubuntu latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch
    # Installing Wapiti using a virtual environment
    # https://github.com/wapiti-scanner/wapiti/blob/master/INSTALL.md
    - name: "Installing Wapiti using a virtual environment"
      run: |
        python -m venv wapiti3
        ./wapiti3/bin/activate
        git clone https://github.com/wapiti-scanner/wapiti.git
        python3 setup.py install
        # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
        # use the SQL, XSS and XXE modules when scanning the target.
        wapiti -u http://testphp.vulnweb.com -m sql,xss,xxe
        wapiti -u http://testphp.vulnweb.com -m sql,xss,xxe
        deactivate        
    - name: "Installing Wapiti using a virtual environment - pip"
      run: |
        python -m venv wapiti3
        ./wapiti3/bin/activate
        git clone https://github.com/wapiti-scanner/wapiti.git
        pip install wapiti3
        deactivate         
    - name: "Installing Wapiti without virtual environment"
      run: |
        git clone https://github.com/wapiti-scanner/wapiti.git
        python3 setup.py install
        deactivate
    - name: "Installing Wapiti without virtual environment - pip"
      run: |
        git clone https://github.com/wapiti-scanner/wapiti.git
        pip install wapiti3
        deactivate

  ubuntu-latest-job:
    name: "docker vuln scanners  ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "archlinux/blackarch"
      dockerfilename: "Dockerfile.archlinux.blackarch"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker pull archlinux container-diff"
      run: |
        sudo docker pull ${distribution}/${version}
        docker image ls  
    - name: "docker build archlinux base"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename} 
        docker image ls
        docker image history ${name}/${version} 
        docker system df -v               
        docker image inspect ${name}/${version} 
    - name: "docker scan trivy archlinux base "
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename} 
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
        trivy image ${name}/${version}

    - name: "docker scan trivy archlinux base "
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename} 
        curl -L https://raw.githubusercontent.com/jgsqware/clairctl/master/install.sh | sudo sh

        trivy image ${name}/${version}

  # ubuntu-latest-job:
  #   name: "docker archlinux ubuntu latest"
  #   runs-on: ubuntu-latest
  #   env:
  #     distribution: "archlinux" #https://hub.docker.com/_/archlinux
  #     version: "latest"
  #     name: "archlinux/base"
  #     dockerfilename: "Dockerfile.archlinux"      
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch   
  #   - name: "docker pull archlinux"
  #     run: sudo docker pull ${distribution}:${version}  && sudo docker image ls  
  #   - name: "docker build archlinux base"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename}
  #       docker image ls
  #       docker image history ${name}/${version}
  #       docker system df -v               
  #       docker image inspect ${name}/${version}
  #   - name: "docker build archlinux network security"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t archlinux:netsec . --file dockerfiles/Dockerfile.archlinux.networksecurity 
  #       docker image ls
  #       docker image history archlinux:netsec
  #       docker system df -v               
  #       docker image inspect archlinux:netsec        
  #   # - name: "run docker ansible local playbook archlinux"
  #   #   run: sudo docker run -e ANSIBLE_FORCE_COLOR=1 --privileged --volume="${PWD}":/home/ansible:ro ${name} ansible-playbook -vvv /home/ansible/playbook.yml --syntax-check -i ./localhost         
  #   # - name: "deploy nxlog"
  #   #   run: sudo make deploy-nxlog-2004 
                         

  # # ubuntu-2004-job:
  # #   name: "nxlog ubuntu  20.04"
  # #   runs-on: ubuntu-latest
  # #   steps:
  # #   - uses: actions/checkout@v2
  # #   - name: "os fingerprinting"
  # #     run: |
  # #       hostnamectl status
  # #       lsb_release -a
  # #       lsb_release -d
  # #       cat /etc/lsb-release
  # #       cat /etc/issue
  # #       cat /etc/os-release
  # #       sudo apt-get install -y neofetch && neofetch   
  # #   - name: "deploy nxlog"
  # #     run: sudo make deploy-nxlog-2004  
        


  # # ubuntu-1804-job:
  # #   name: "nxlog ubuntu-18.04"
  # #   runs-on: ubuntu-18.04
  # #   steps:
  # #   - uses: actions/checkout@v2
  # #   - name: "os fingerprinting"
  # #     run: |
  # #       hostnamectl status
  # #       lsb_release -a
  # #       lsb_release -d
  # #       cat /etc/lsb-release
  # #       cat /etc/issue
  # #       cat /etc/os-release
  # #       sudo apt-get install -y neofetch && neofetch    
  #   # - name: "deploy nxlog"
  #     # The following packages have unmet dependencies:
  #     # mono-xsp4 : Depends: mono-xsp4-base (= 4.2-2.1) but it is not going to be installed
  #     # run: sudo make deploy-nxlog 




