name: "docker forensics CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-apache2-latest-job:
    name: "apache2 ubuntu latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch  
    - name: "os fingerprinting"
      run: |
        docker run -d --name apache2-container -e TZ=UTC -p \
          8080:80 ubuntu/apache2:2.4-21.10_beta
        netstat -plan | grep ":8080"
        netstat -plan
        # curl http://localhost:8080
        docker logs -f apache2-container
        # interactive shell
        # docker exec -it apache2-container /bin/bash

  ubuntu-container-diff-latest-job:
    name: "container-diff ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "archlinux/blackarch"
      dockerfilename: "Dockerfile.archlinux.blackarch"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker pull archlinux container-diff"
      run: |
        # sudo docker pull ${distribution}/${version}
        sudo docker pull ${distribution}
        docker image ls  
        pacman -S container-diff
        container-diff analyze ${distribution}
    - name: "docker build archlinux base"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename} 
        docker image ls
        docker image history ${name}/${version} 
        docker system df -v               
        docker image inspect ${name}/${version} 
    - name: "docker build archlinux base"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename} 
        curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64
        install container-diff-linux-amd64 /usr/local/bin/container-diff
        container-diff analyze ${name}/${version}

  # ubuntu-latest-job:
  #   name: "docker archlinux ubuntu latest"
  #   runs-on: ubuntu-latest
  #   env:
  #     distribution: "archlinux" #https://hub.docker.com/_/archlinux
  #     version: "latest"
  #     name: "archlinux/base"
  #     dockerfilename: "Dockerfile.archlinux"      
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch   
  #   - name: "docker pull archlinux"
  #     run: sudo docker pull ${distribution}:${version}  && sudo docker image ls  
  #   - name: "docker build archlinux base"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename}
  #       docker image ls
  #       docker image history ${name}/${version}
  #       docker system df -v               
  #       docker image inspect ${name}/${version}
  #   - name: "docker build archlinux network security"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t archlinux:netsec . --file dockerfiles/Dockerfile.archlinux.networksecurity 
  #       docker image ls
  #       docker image history archlinux:netsec
  #       docker system df -v               
  #       docker image inspect archlinux:netsec        
  #   # - name: "run docker ansible local playbook archlinux"
  #   #   run: sudo docker run -e ANSIBLE_FORCE_COLOR=1 --privileged --volume="${PWD}":/home/ansible:ro ${name} ansible-playbook -vvv /home/ansible/playbook.yml --syntax-check -i ./localhost         
  #   # - name: "deploy nxlog"
  #   #   run: sudo make deploy-nxlog-2004 
                         

  # # ubuntu-2004-job:
  # #   name: "nxlog ubuntu  20.04"
  # #   runs-on: ubuntu-latest
  # #   steps:
  # #   - uses: actions/checkout@v2
  # #   - name: "os fingerprinting"
  # #     run: |
  # #       hostnamectl status
  # #       lsb_release -a
  # #       lsb_release -d
  # #       cat /etc/lsb-release
  # #       cat /etc/issue
  # #       cat /etc/os-release
  # #       sudo apt-get install -y neofetch && neofetch   
  # #   - name: "deploy nxlog"
  # #     run: sudo make deploy-nxlog-2004  
        


  # # ubuntu-1804-job:
  # #   name: "nxlog ubuntu-18.04"
  # #   runs-on: ubuntu-18.04
  # #   steps:
  # #   - uses: actions/checkout@v2
  # #   - name: "os fingerprinting"
  # #     run: |
  # #       hostnamectl status
  # #       lsb_release -a
  # #       lsb_release -d
  # #       cat /etc/lsb-release
  # #       cat /etc/issue
  # #       cat /etc/os-release
  # #       sudo apt-get install -y neofetch && neofetch    
  #   # - name: "deploy nxlog"
  #     # The following packages have unmet dependencies:
  #     # mono-xsp4 : Depends: mono-xsp4-base (= 4.2-2.1) but it is not going to be installed
  #     # run: sudo make deploy-nxlog 




