name: "w3af CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-latest-w3af-job:
    name: "w3af ubuntu latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch
    # http://w3af.org/download
    - name: "Installing w3af"
      run: |
        git clone --depth 1 https://github.com/andresriancho/w3af.git && cd w3af 
        # https://dvwa.co.uk/
        grep "localhost" scripts/dvwa.w3af
        sed 's%localhost%dvwa.co.uk%g' scripts/dvwa.w3af
        grep "dvwa.co.uk" scripts/dvwa.w3af
        # ./w3af_console -s scripts/dvwa.w3af

# https://github.com/snsttr/diwa
  ubuntu-latest-diwa-job:
    name: "diwa ubuntu latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch
    # http://w3af.org/download
    - name: "Installing w3af"
      run: |
        git clone https://github.com/snsttr/diwa && cd diwa
        docker build -t diwa .
        docker run -p 8080:80 -d diwa:latest
        netstat -plan | grep ":8080"
        netstat -plan
        curl http://localhost:8080
        # docker logs -f apache2-container
        # interactive shell
        # docker exec -it apache2-container /bin/bash